openapi: 3.0.3
info:
  title: El Tenedor 4V API
  description: API para mantener una BBDD de Restaurante cercanos al Instituto 4V
  contact:
    email: miguel_goyena@cuatrovientos.org
  version: 0.1.1
servers:
  - url: http://localhost:8000
tags:
  - name: restaurants
    description: Everything about restaurants
  - name: restaurants-types
    description: Everything about the types of restaurantes
paths:
  /restaurants:
    get:
      tags:
        - restaurants
      summary: Finds All Restaurants
      operationId: findAllRestaurants
      parameters:
        - name: typeName
          in: query
          description: Filtrar por el nombre del tipo (Italiano, Oriental, Latino)
          required: false
          schema:
            type: string
            enum: 
              - Italiano
              - Oriental
              - Latino
      responses:
        '200':
          description: Returns OK in all restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurante'
        '400':
          description: Invalid restaurant type supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Any problem in server

    # --- AQUÍ EMPIEZA EL POST ---
    post:
      tags:
        - restaurants
      summary: Create a new Restaurant
      operationId: newRestaurants
      requestBody:
        description: Objeto RestauranteDTO que se va a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Restaurante'
      responses:
        '200':
          description: Restaurante creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurante'
        '422':
          description: Error de validación (Unprocessable Content). Los datos enviados no coinciden con el DTO.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error

  /types/restaurant:
    get:
      tags:
        - restaurants-types
      summary: Finds All Restaurant Types
      operationId: findAllRestaurantTypes
      responses:
        '200':
          description: Returns OK with all restaurant types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RestaurantType'
        '500':
          description: Any problem in server / Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Restaurante:
      type: object
      required:
        - id
        - name
        - resType
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: La Tagliatella
        # CAMBIO IMPORTANTE: Debe llamarse igual que tu variable PHP ($resType)
        resType:
          $ref: '#/components/schemas/RestaurantType'
    
    RestaurantType:
      type: object
      required:
        - id
        - typeName
      properties:
        id:
          type: integer
          format: int64
          example: 10
        typeName:
          type: string
          example: Oriental
    
    ErrorResponse:
      type: object
      required:
        - code
        - description
      properties:
        code:
          type: string
          example: "INVALID_TYPE"
        description:
          type: string
          example: "El tipo de restaurante proporcionado no es válido."